-- =====================================================================
-- 061_agendas_entrantes.sql
-- Ventas, fase 3: tabla de entrada para los webhooks de agenda de GHL.
--
-- Guarda cada webhook TAL CUAL llega, sin procesar. Es aparte de
-- fin_llamadas a proposito: mientras el Sheet siga activo, la sync
-- reemplaza fin_llamadas cada 15 min y no queremos mezclar.
-- Con esta tabla comparamos webhook contra Sheet antes del corte.
--
-- Escribe solo la Edge Function ventas-agenda (service role, salta RLS).
-- Lee solo el fundador.
-- Idempotente. Sin begin/commit. Controles abajo, de a uno.
-- =====================================================================

create table if not exists fin_agendas_entrantes (
  id            bigint generated by default as identity primary key,
  recibido_en   timestamptz not null default now(),
  cliente_id    text        not null references crm_clients(id),
  origen_wf     text,
  ghl_cita_id   text,
  payload       jsonb       not null,
  procesado_en  timestamptz,
  llamada_id    bigint      references fin_llamadas(id) on delete set null,
  error         text,
  constraint fin_agendas_payload_ck check (jsonb_typeof(payload) = 'object')
);

comment on table  fin_agendas_entrantes is 'Webhooks de agenda de GHL, crudos. Fase 3 de Ventas: se comparan contra el Sheet antes del corte';
comment on column fin_agendas_entrantes.origen_wf is 'Nombre del workflow de GHL que mando el webhook (parametro wf de la URL)';
comment on column fin_agendas_entrantes.ghl_cita_id is 'ID de la cita si la funcion lo pudo encontrar en el payload. Puede quedar null hasta conocer el formato real';

create index if not exists fin_agendas_cliente_idx on fin_agendas_entrantes (cliente_id, recibido_en desc);
create index if not exists fin_agendas_cita_idx    on fin_agendas_entrantes (cliente_id, ghl_cita_id) where ghl_cita_id is not null;

alter table fin_agendas_entrantes enable row level security;

drop policy if exists fin_agendas_lectura on fin_agendas_entrantes;
create policy fin_agendas_lectura on fin_agendas_entrantes for select using (es_fundador());

-- =====================================================================
-- CONTROLES (de a uno)
-- =====================================================================

-- C1. La tabla existe, vacia y con RLS: 0 | true.
-- select (select count(*) from fin_agendas_entrantes) as filas,
--        (select relrowsecurity from pg_class where relname = 'fin_agendas_entrantes') as rls;

-- C2. Solo una politica, de lectura: 1 fila, SELECT.
-- select policyname, cmd from pg_policies where tablename = 'fin_agendas_entrantes';
